# -*- coding: utf-8 -*-
"""14_may(ridge,lasso,elastic_net)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZJh2ZaHB_LUZ9XgEP-nd25a51Ji20xO9
"""

tips data (lr ridge lasso elstic net)

import pandas as pd
import numpy as np

df = pd.read_csv("/content/tips - tips.csv")
df.head(2)

df.isnull().sum()  #

from sklearn.preprocessing import LabelEncoder

lb=LabelEncoder()

df['sex']=lb.fit_transform(df['sex'])
df['smoker']=lb.fit_transform(df['smoker'])
df['day'] = lb.fit_transform(df['day'])
df['time'] = lb.fit_transform(df['time'])

# smoker  	day  time

x=df.drop(columns=['total_bill'])
y=df['total_bill']

#train_test_split

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

# linearregression

from sklearn.linear_model import LinearRegression

lr=LinearRegression()

lr.fit(x_train,y_train)

y_pred = lr.predict(x_test)

from sklearn.metrics import r2_score

r2_score(y_test,y_pred)

# ridge

from sklearn.linear_model import Ridge, Lasso , ElasticNet

from sklearn.metrics import mean_squared_error ,r2_score

Ridge_model = Ridge(alpha=0.1)
Ridge_model.fit(x_train,y_train)

Ridge_pred = Ridge_model.predict(x_test)

Ridge_mse = mean_squared_error(y_test,Ridge_pred)
Ridge_r2 = r2_score(y_test,Ridge_pred)

print("MSE :",Ridge_mse)
print("R2 Score :",Ridge_r2)
print("Coefficients :",Ridge_model.coef_)

# lasso

lasso_model = Lasso(alpha=0.1)
lasso_model.fit(x_train,y_train)

lasso_pred = lasso_model.predict(x_test)

lasso_mse = mean_squared_error(y_test,lasso_pred)
lasso_r2 = r2_score(y_test,lasso_pred)
print("MSE :",lasso_mse)
print("R2 Score :",lasso_r2)
print("Coefficients :",lasso_model.coef_)

# elastic_net

Elastic_model = ElasticNet(alpha=0.1,l1_ratio=0.5)
Elastic_model.fit(x_train,y_train)

Elastic_pred = Elastic_model.predict(x_test)

Elastic_mse = mean_squared_error(y_test,Elastic_pred)
Elastic_r2 = r2_score(y_test,Elastic_pred)
print("MSE :",Elastic_mse)
print("R2 Score :",Elastic_r2)
print("Coefficients :",Elastic_model.coef_)

from sklearn.linear_model import RidgeCV
Ridge_cv = RidgeCV(alphas=[0.001, 0.01, 0.1, 1, 10, 100],cv = 5)

#cross validation
from sklearn.linear_model import LassoCV

Lasso_cv = LassoCV(alphas=[0.001,0.01,0.1,1,10],cv = 5,random_state=42)

Lasso_cv.fit(x_train, y_train)

print("Best Alpha:",Lasso_cv.alpha_)

Lasso_cv.fit(x_train,y_train)

# elasticnetcv cross validation

from sklearn.linear_model import ElasticNetCV

Elastic_cv = ElasticNetCV(l1_ratio=[0.1,0.3,0.5,0.7,0.9,1],alphas=[0.001,0.01,0.1,1,10],
     cv=5,random_state=40)

Elastic_cv.fit(x_train,y_train)

print("Best Alpha:",Elastic_cv.alpha_)
print("Best L1 Ratio:",Elastic_cv.l1_ratio_)

# Ridge Regression :-Ridge Regression ek regularization technique hai jo model ke coefficients ko shrink karti hai taaki
#  overfitting kam ho aur model better generalize kare. isme L2 penaltty use hoti hai.

# Lasso Regression:- Lasso Regression ek regularization technique hai jo coefficients ko shrink karne
#  ke saath kuch coefficients ko exactly zero bhi kar deti hai, isliye ye feature selection me useful hoti hai.
#  isme L1 penaltty use hoti hai.

# Elastic Net :-
# Elastic Net Regression Ridge aur Lasso dono ka combination hai.
# Ye L1 aur L2 dono penalties use karta hai, jisse overfiting bhi kam hoti hai aur feature selection bhi ho jata hai

# mae, mse rmse

# MAE (Mean Absolute Error) :- ye  evaluation metrices hai jo predicted values or actual values ke beech
# average absolute diff. ko measure karta hai.
#  Ye batata hai ki model average me kitni error de rha h

# MSE (Mean Squared Error) :-MSE ek evaluation metrices hai jo predicted aur actual values ke diff. ka square lekar
#  unka average nikalta hai. Badi errors ko zyada penalty milti hai.

# RMSE (Root Mean Squared Error) :- RMSE, MSE ka square root hota hai.
#  Ye error ko original unit me dikhata hai aur large errors ko zyada imp. deta hai.