# -*- coding: utf-8 -*-
"""15-april-practice

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XhG7FuVHJ6q549grEg61N5P4TKQ59MXn
"""

# this is coffee datasset . You have to :
# 1. Check missing data if present then handling it.
# 2. Encode data
# 3. Apply Standardization
# 4. Apply Normalization
# 5. Filter 30-40 Indexed data using pandas
# 6. Rename a column name

import numpy as np
import pandas as pd

df = pd.read_csv("/content/Coffe_sales - Coffe_sales.csv")

df.head()

df.shape

df.isnull().sum()

df['cash_type'].value_counts()

df['coffee_name'].value_counts()

df['Time_of_Day'].value_counts()

df['Weekday'].value_counts()

df['Month_name'].value_counts()

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['cash_type'] = le.fit_transform(df['cash_type'])
df['coffee_name'] = le.fit_transform(df['coffee_name'])
df['Time_of_Day'] = le.fit_transform(df['Time_of_Day'])
df['Weekday'] = le.fit_transform(df['Weekday'])
df['Month_name'] = le.fit_transform(df['Month_name'])

df.head()

"""ordinal encoding"""

# df1 = pd.read_csv('/content/Coffe_sales - Coffe_sales.csv')

# df.head()

# from sklearn.preprocessing import OrdinalEncoder

# oe = OrdinalEncoder(categories=[['Morning', 'Afternoon', 'Night'],['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
#                     ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']])

# oe_ar = oe.fit_transform(df1[['Time_of_Day', 'Weekday','Month_name']])
# oe_ar

# oe_df1 = pd.DataFrame(oe_ar, columns=df1[['Time_of_Day', 'Weekday','Month_name']].columns)
# oe_df1.head(2)

# Apply Standardization

x = df.drop(columns=['money','Date','Time'])
y = df['money']

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y,test_size=0.20, random_state=42)

np.round(x_train.describe(), 2)

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

x_train_sc = sc.fit_transform(x_train)

new_x_train = pd.DataFrame(x_train_sc, columns=x_train.columns)

np.round(new_x_train.describe(), 2)

# . Apply Normalization

x1 = df.drop(columns=['money','Date','Time'])
y1 = df['money']

from sklearn.model_selection import train_test_split

x1_train, x1_test, y1_train, y1_test = train_test_split(x1, y1, test_size=0.2, random_state=42)

x1_train.describe()

from sklearn.preprocessing import MinMaxScaler

mn = MinMaxScaler()

x1_train_mn = mn.fit_transform(x1_train)

x1_train_mn

x1_train_mn_df = pd.DataFrame(x1_train_mn, columns=x1_train.columns)

np.round(x1_train_mn_df.describe(), 2)

df.iloc[30:40, :]  #Filter 30-40 Indexed data using pandas

df.rename(columns={'Date':'Dates'}, inplace=True)  #. Rename a column name