# -*- coding: utf-8 -*-
"""column_transformer_20april

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_cVC7YZzGfzB39oq79IUUYkYZSywWZ7x

# column Transformer
"""

import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer # for filling missing values
from sklearn.preprocessing import OneHotEncoder  ### encoding
from sklearn.preprocessing import OrdinalEncoder  # encoding

df = pd.read_csv("/content/covid_toy - covid_toy (1).csv")

df

df.isnull().sum()

from sklearn.model_selection import train_test_split

x_train , x_test , y_train , y_test = train_test_split((df.drop(columns=['has_covid'])),df['has_covid'],test_size=0.2)

x_train

"""# manually type output"""

# adding simple imputer to fever column
si = SimpleImputer(strategy="mean")
x_train_fever = si.fit_transform(x_train[['fever']])
 # also the tet data
x_test_fever = si.fit_transform(x_test[['fever']])
x_train_fever.shape

#ordinal encoding ---> cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
x_train_cough = oe.fit_transform(x_train[['cough']])
 # also the test data
x_test_cough = oe.fit_transform(x_test[['cough']])
x_train_cough.shape

# onehotencoding --> gender , city
ohe = OneHotEncoder(drop='first',sparse_output=False)
x_train_gender_city = ohe.fit_transform(x_train[['gender','city']])
 # also the test data
x_test_gender_city = ohe.fit_transform(x_test[['gender','city']])
x_train_gender_city.shape

# extracting age
x_train_age = x_train.drop(columns=['gender','fever','cough','city']).values
 # also the test data
x_test_age = x_test.drop(columns=['gender','fever','cough','city']).values

x_train_age.shape

x_train_transformed = np.concatenate((x_train_age,x_train_fever,x_train_gender_city,x_train_cough),axis=1)

# x_test_trasformed = np.concatenate((x_test_age, x_test))

x_train_transformed.shape

"""# by the help of column Transformer"""

from sklearn.compose import ColumnTransformer

transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']), # in a fever column by the help of SI we fill missing values by mean , median , mode.
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']), # in a cough column by the help of OE
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])],remainder ='passthrough') # in a gender and city column
    # remainder = pasthrough --->it means rest all the columns remain same

transformer.fit_transform(x_train).shape



"""# insurance data"""

df = pd.read_csv("/content/insurance - insurance.csv")

df.head(3)

df.isnull().sum()

from sklearn.model_selection import train_test_split

x_train , x_test , y_train , y_test = train_test_split((df.drop(columns=['smoker'])),df['smoker'],test_size=0.2)

x_train

y_train

"""by the help of column transformer

"""

from sklearn.compose import ColumnTransformer

transformer = ColumnTransformer(transformers=[
    ('tnf1',OneHotEncoder(drop='first'),['sex','region'])],remainder ='passthrough')

transformer.fit_transform(x_train).shape

