# -*- coding: utf-8 -*-
"""encoding

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g6uG0cDFKYNAqTkTqBdMPwsfo3PlYyxq
"""

# encoding --> transform your categorical data into numerical data

# (1) label encoder ---> has_covid['yes' , 'no']---> value_counts()---> encode ---> has_covid[1,0]

import numpy as np
import pandas as pd

df = pd.read_csv("/content/covid_toy - covid_toy (1).csv")
df

df.head()

df.dropna()

from sklearn.preprocessing import LabelEncoder

lb = LabelEncoder()

df['gender'] = lb.fit_transform(df['gender'])

df['cough'] = lb.fit_transform(df['cough'])
df['city'] = lb.fit_transform(df['city'])
df['has_covid'] = lb.fit_transform(df['has_covid'])

df.head()

x = df.drop(columns =['has_covid'])

y = df['has_covid']

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

# apply standarddization for converting data into normal distribution

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

x_train_sc = sc.fit_transform(x_train)
x_test_sc = sc.transform(x_test)

x_train_new = pd.DataFrame(x_train_sc, columns=x_train.columns)

np.round(x_train_new.describe(), 2)

df = pd.read_csv("/content/tips - tips.csv")
df.head()

df = df.dropna()

from sklearn.preprocessing import LabelEncoder

lb = LabelEncoder()

df['sex'] = lb.fit_transform(df['sex'])
df['smoker'] = lb.fit_transform(df['smoker'])
df['day'] = lb.fit_transform(df['day'])
df['time'] = lb.fit_transform(df['time'])

df.head()

x = df.drop(columns =['total_bill'])
y = df['total_bill']

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

# apply normalization

from sklearn.preprocessing import MinMaxScaler

mn = MinMaxScaler()

x_train_mn = mn.fit_transform(x_train)
x_test_mn = mn.transform(x_test)

x_train_new = pd.DataFrame(x_train_mn, columns=x_train.columns)

np.round(x_train_new.describe(), 2)

# insurance data ----> label encoder , standardscaler

df = pd.read_csv("/content/insurance - insurance.csv")

df.head()

df.dropna()

from sklearn.preprocessing import LabelEncoder

lb = LabelEncoder()

df['sex'] = lb.fit_transform(df['sex'])
df['smoker'] = lb.fit_transform(df['smoker'])
df['region'] = lb.fit_transform(df['region'])

df.head()

x = df.drop(columns=['charges'])
y = df['charges']

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

x_train_sc = sc.fit_transform(x_train)
x_test_sc = sc.transform(x_test)

x_train_new = pd.DataFrame(x_train_sc, columns=x_train.columns)

np.round(x_train_new.describe(), 2)