# -*- coding: utf-8 -*-
"""how to remove outliers

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JIzrxRUZh1m58uqBmKStJWzkRjNlLNPE
"""

import numpy as np
import pandas as pd

df = pd.read_csv("/content/newplacementdata - newplacementdata.csv")

df.head()

# even = ((n/2)+1))/2
# odd = ((n/2)+1)

import matplotlib.pyplot as plt
import seaborn as sns

df['placement_exam_marks'].describe()

sns.boxplot(x= df['placement_exam_marks'])

# finding the IQR
percentile25 = df['placement_exam_marks'].quantile(0.25)
percentile75 = df['placement_exam_marks'].quantile(0.75)

percentile25

percentile75

IQR = percentile75 -percentile25
IQR

upper_limit = percentile75 + 1.5*IQR
upper_limit

lower_limit = percentile25 - 1.5*IQR
lower_limit

"""# finding our outliers"""

df[df['placement_exam_marks']> upper_limit]

df[df['placement_exam_marks']<lower_limit]

# trimming ----> 4(lower)....1 , upper(25)......(50) ------> here 1,50 are ouliers ----> lower(4) <----> upper(25) mid data
# capping -----> 4(lower)....1,upper(25).....(50)----> capping lower point (1)
# u[pper point upper point(50) ---> range exapand  --> outliers remive.

# trimming outliers removing technique 1

newdf = df[df['placement_exam_marks']<upper_limit]

newdf

# comparison

plt.figure(figsize = (15,5))
plt.subplot(222)
sns.boxplot(x= df['placement_exam_marks'])
plt.subplot(224)
sns.boxplot(x=newdf['placement_exam_marks'])
plt.show()

#capping(outlier removing technique 2)

new_df_cap = df.copy()

#min = 5 , max 15
# min 4,3,1
# max = 20 , 30 , 50
# updated_min_value = 1
# updated_max_value = 50

new_df_cap['placement_exam_marks'] = np.where(
    new_df_cap['placement_exam_marks'] > upper_limit,
    upper_limit,
    np.where(
        new_df_cap['placement_exam_marks'] < lower_limit,
        lower_limit,
        new_df_cap['placement_exam_marks'])
)

new_df_cap

plt.figure(figsize = (15,8))
plt.subplot(222)
sns.boxplot(x= df['placement_exam_marks'])
plt.subplot(224)
sns.boxplot(x=new_df_cap['placement_exam_marks'])
plt.show()

titanic age

df = pd.read_csv("/content/titanic - titanic.csv")

df.head()

df['Age'].describe()

sns.boxplot(x= df['Age'])

Q1 = df['Age'].quantile(0.25)

Q3 = df['Age'].quantile(0.75)
IQR = Q3 - Q1

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

df[df['Age']> upper_limit]

df[df['Age']<lower_limit]

new_df = df[df['Age']<upper_limit]

new_df

plt.figure(figsize = (15,5))
plt.subplot(222)
sns.boxplot(x= df['Age'])
plt.subplot(224)
sns.boxplot(x=new_df['Age'])
plt.show()

print(df.shape)
print(new_df.shape)

# capping

new2_df_cap = df.copy()

new2_df_cap['Age'] = np.where(
    new2_df_cap['Age'] > upper_limit,
    upper_limit,
    np.where(
        new2_df_cap['Age'] < lower_limit,
        lower_limit,
        new2_df_cap['Age'])
)

new2_df_cap

plt.figure(figsize = (15,8))
plt.subplot(222)
sns.boxplot(x= df['Age'])
plt.subplot(224)
sns.boxplot(x=new2_df_cap['Age'])
plt.show()