# -*- coding: utf-8 -*-
"""logistic_Regression

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ozjJZK4DOorGaVouYOyayY8n-7E0HgvM
"""

# logisitic regression model ----> supervised ml model , used for classification problems,
# internally activation function ----> classes or sub-categories ---> problability

# probability = 0 to 1
# if x>0.5 :
#   return 1
# else :
#     return 0

import numpy as np
import pandas as pd

df = pd.read_csv("/content/covid_toy - covid_toy (1).csv")

df.head(2)

# Fever column ki missing values ko mean se bharne ke liye
df['fever'] = df['fever'].fillna(df['fever'].mean())

from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()

df['gender'] = lb.fit_transform(df['gender'])
df['cough'] = lb.fit_transform(df['cough'])
df['city'] = lb.fit_transform(df['city'])
df['has_covid'] = lb.fit_transform(df['has_covid'])

x = df.drop(columns=['has_covid'])
y = df['has_covid']

from sklearn.model_selection import train_test_split

x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=42)

from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()

lr.fit(x_train,y_train)

y_pred = lr.predict(x_test)

from sklearn.metrics import accuracy_score

accuracy_score(y_test , y_pred)

# attrition

df = pd.read_csv("/content/Attrition - Attrition.csv")

df.head(2)

EducationField,Department,BusinessTravel,	Attrition,gender , JobRole,MaritalStatus

df.isnull().sum()

# In columns ko drop kar dijiye
df = df.drop(columns=['EmployeeCount', 'EmployeeNumber', 'Over18', 'StandardHours'])

df['EducationField'] = lb.fit_transform(df['EducationField'])
df['Department'] = lb.fit_transform(df['Department'])
df['BusinessTravel'] = lb.fit_transform(df['BusinessTravel'])
df['Attrition'] = lb.fit_transform(df['Attrition'])
df['Gender'] = lb.fit_transform(df['Gender'])
df['JobRole'] = lb.fit_transform(df['JobRole'])
df['MaritalStatus'] = lb.fit_transform(df['MaritalStatus'])
df['OverTime'] = lb.fit_transform(df['OverTime'])

df.head()

x = df.drop(columns=['Attrition'])
y = df['Attrition']

from sklearn.model_selection import train_test_split

x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=42)

from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()

lr.fit(x_train,y_train)

y_pred = lr.predict(x_test)

from sklearn.metrics import accuracy_score

accuracy_score(y_test , y_pred)

# churn_modelling

df = pd.read_csv("/content/Churn_Modelling - Churn_Modelling.csv")

df.head(2)



df.isnull().sum()

df = df.drop(columns=['RowNumber', 'CustomerId', 'Surname'])

df['Geography'] = lb.fit_transform(df['Geography'])
df['Gender'] = lb.fit_transform(df['Gender'])

df.head()

x = df.drop(columns=['Exited'])
y = df['Exited']

from sklearn.model_selection import train_test_split

x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=42)

from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()

lr.fit(x_train,y_train)

y_pred = lr.predict(x_test)

from sklearn.metrics import accuracy_score

accuracy_score(y_test , y_pred)