# -*- coding: utf-8 -*-
"""machinelearning_data_dividation_day1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D4eNCDOIGSA8Z4Sc5AHiwDFFID0mXeRd

**machine learning (data dividation)**
"""

# machine learning -------
# data(50) -----> x (input data),y(target data)
# x ----> x_train , x_test
# y ----> y_train , y_test
# for matching training we will pass(x_train,y_train)
# for matching testing we will pass(x_test) - y_pred

1+1 = 2
1+2=3
1+4=5
1+6=7
1+7=8
1+8=9

# x = (1+1 ,!+2,1+4,.......,1+8)
# y=(2,3,5,7,8,9)
# x_train = (1+1,1+2,1+4,1+6)
# x_test =(1+7,1+8)
# y_train =(2,3,5,7)
# y_test =(8,9)

import pandas as pd
df = pd.read_csv("/content/covid_toy - covid_toy (1).csv")
df.head(3)

df.shape

df.isnull().sum()

df['fever']= df['fever'].fillna(df['fever'].mean())

df.isnull().sum()



x = df.drop(columns =['has_covid'])  #### input data
x

y = df['has_covid']  ## target or output dat
y

from sklearn.model_selection import train_test_split

x_train , x_tast, y_train , y_test = train_test_split(x,y,test_size = 0.2, random_state=42)

print("total data shape :" , df.shape)
print("------------------------------")
print("input data shape :", x.shape)
print("x_train data shape :", x_train.shape)
print("x_test data shape :", x_tast.shape)
print("--------------------------------")
print("output data shape :", y.shape)
print("y_train data shape :", y_train.shape)
print("y_test data shape :", y_test.shape)



df = pd.read_csv("/content/placement - placement (1).csv")
df.head(3)

df.isnull().sum()

x = df.drop(columns =['placed'])  #### input data
x

y = df['placed']  ## target or output dat
y

x_train , x_tast, y_train , y_test = train_test_split(x,y,test_size = 0.2, random_state=42)

print("total data shape :" , df.shape)
print("------------------------------")
print("input data shape :", x.shape)
print("x_train data shape :", x_train.shape)
print("x_test data shape :", x_tast.shape)
print("--------------------------------")
print("output data shape :", y.shape)
print("y_train data shape :", y_train.shape)
print("y_test data shape :", y_test.shape)