# -*- coding: utf-8 -*-
"""model_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B-0ZboBrFzyCocjMLDDymGz2FEfWXkPj
"""

#workflow of machine learning ::_>
#Data ingestion --> data cleaning and preprocessing --> select best model according to data
# model training --> model prediction --> model performance evelvation

# types of ml models ---

# 1> supervised --> will trained on label data
# 2> unsupervised --> will train on unlabel data

#!!!! 1> SUPERVISED ML MODEL

# IF OUR TARGET DATA IS :::
#(1)NUMERICAL : linearregrssion,DT regressor, RF regressor
#(2)CATEGORICAL ---> LogisticRegression,DT classifier,RF classifier ,Naive Bayes,SVM,KNN

#1 LINEAR REGRESSION

import pandas as pd
import numpy as np

df=pd.read_csv('/content/insurance - insurance.csv')

df.head(2)

df.isnull().sum()

from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()

df['sex']=lb.fit_transform(df['sex'])
df['smoker']=lb.fit_transform(df['smoker'])
df['region']=lb.fit_transform(df['region'])

x=df.drop(columns=['charges'])
y=df['charges']

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

from sklearn.linear_model import LinearRegression

lr=LinearRegression()

lr.fit(x_train,y_train)

y_pred=lr.predict(x_test)

#y_pred
#y_test

from sklearn.metrics import r2_score

r2_score(y_test,y_pred)

tp=pd.read_csv('/content/tips - tips.csv')

tp.head(1)

#tp.isnull().sum()

tp['sex']=lb.fit_transform(tp['sex'])
tp['smoker']=lb.fit_transform(tp['smoker'])
tp['day']=lb.fit_transform(tp['day'])
tp['time']=lb.fit_transform(tp['time'])

x=tp.drop(columns=['total_bill'])
y=tp['total_bill']

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

lr.fit(x_train,y_train)

y_pred=lr.predict(x_test)

r2_score(y_test,y_pred)