# -*- coding: utf-8 -*-
"""normalization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OBcZx0j6F-ABKTyz0d64tmgJ9RVnVMVY
"""

# normalization ----> using MinMaxScaling()  --->
# data Min_value = 0, Max_value = 1

# play store ----> different - different apps ---> 1 app download 4.2k , 1 app downloads 2.3 m,, 1 app download 650
# in this condition , if i apply any operation , if i apply any operation , then it will return huge number and we cannot perform any visluzation it will create

import numpy as np
import pandas as pd

df = pd.read_csv("/content/covid_toy - covid_toy (1).csv")

df = df.dropna()

df.isnull().sum()

df['fever'] = df['fever'].fillna(df['fever'].mean())

# step 1 convert categorical data tpo numerical data

df['cough'] = df['cough'].map({'Mild':0,'Strong':1})
df['has_covid'] = df['has_covid'].map({'No':0,'Yes':1})
df['gender'] = df['gender'].map({'Male':1,'Female':0})

df['city'] = df['city'].map({'Kolkata':1,'Delhi':2,'Mumbai':3,'Bangalore':0})

df.head(2)

# step 2 data dividation

x = df.drop(columns=['has_covid'])
x ## input data

y = df['has_covid']
y ## target data

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

np.round(x_train.describe(),2)

# step 3 apply minmaxscalling

from sklearn.preprocessing import MinMaxScaler

mn = MinMaxScaler()

x_train_mn = mn.fit_transform(x_train)

x_train_new = pd.DataFrame(x_train_mn,columns=x_train.columns)

np.round(x_train_new.describe(),2)

# practice data 2

df = pd.read_csv("/content/placement - placement (1).csv")

x = df.drop(columns=['placed'])

y = df['placed']

from sklearn.model_selection import train_test_split

x_train , x_test ,y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

np.round(x_train.describe(),2)

# from sklearn.preprocessing import MinMaxScaler

# mn = MinMaxScaler()

x_train_mn = mn.fit_transform(x_train)

x_train_new = pd.DataFrame(x_train_mn,columns=x_train.columns)

np.round(x_train_new.describe(),2)