# -*- coding: utf-8 -*-
"""normal_distribution_day2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z8jmNtW3KEChMB1EcI9toxaP48aTj915
"""

import numpy as np
import pandas as pd

df = pd.read_csv("/content/covid_toy - covid_toy (1).csv")
df.head()

df.isnull().sum()

df['fever'] = df['fever'].fillna(df['fever'].mean())

df.isnull().sum()

df['cough'].value_counts()

df.describe()

df.head(10)

df['cough'] = df['cough'].map({'Mild':0,'Strong':1})
df['has_covid'] = df['has_covid'].map({'No':0,'Yes':1})
df['gender'] = df['gender'].map({'Male':1,'Female':0})

df['city'] = df['city'].map({'Kolkata':1,'Delhi':2,'Mumbai':3,'Bangalore':0})

df.head(10)

df.describe()

x = df.drop(columns=['has_covid'])
x ## input data

y = df['has_covid']
y ## target data

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

np.round(x_train.describe(),2)

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

x_train_sc = sc.fit_transform(x_train)### fit means learn the parameters and the transform means apply on that

x_train_sc

x_train_new = pd.DataFrame(x_train_sc, columns= x_train.columns)

type(x_train_new)

np.round(x_train_new.describe(),2)