# -*- coding: utf-8 -*-
"""ordinal encoding

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15iH7f9KMKLtkyfhK12mbZtompgPt36yA
"""

# ordinal encoding --->
# label encoding ---> column[sub1,syub2,sub3....ubn]--> encode
# ordinal encoding --> column [sub1, sub2,...subn ]--- reaaraange -- encode

import numpy as np
import pandas as pd

df = pd.read_csv("/content/covid_toy - covid_toy (1).csv")

df = df.dropna()

df = df.drop(columns=['city','age','fever'])

x = df.drop(columns =['has_covid'])
y = df['has_covid']

df.head(2)

df.head(2)

from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder()
# categories=[['Male','Female'],['No','Yes'],['Mild','Strong']])

oe_ar = oe.fit_transform(df)

new_df = pd.DataFrame(oe_ar, columns=df.columns)

new_df

# second way

df = pd.read_csv("/content/covid_toy - covid_toy (1).csv")
df.head(2)

df.dropna()

df = df.drop(columns = ['age','fever','city'])

df.head(3)

x = df.drop(columns=['has_covid'])
y = df['has_covid']

x.head()

from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(categories=[
    ['Male', 'Female'],
    ['Mild', 'Strong']])

oe_ar = oe.fit_transform(x)

y.head()

from sklearn.preprocessing import LabelEncoder

lb = LabelEncoder()

y = lb.fit_transform(y)

y

# 🔹 LabelEncoder:
# Jab humare paas single column (target variable) hota hai,
# tab hum LabelEncoder use karte hain.
# Example:
# has_covid ['yes', 'no']  ---> LabelEncoder ---> [1, 0]

# 🔹 OrdinalEncoder:
# Jab humare paas multiple input columns (features) hote hain,
# tab hum OrdinalEncoder use karte hain.
# Example:
# gender ['male', 'female'] ---> [1, 0]
# fever ['mild', 'strong'] ---> [0, 1]

# 🔹 Difference:
# LabelEncoder → sirf y (target column) ke liye
# OrdinalEncoder → X (multiple feature columns) ke liye

# tips data ===>
# target column 'total_bill'
#numerical columns ==> remove
# categorical columns ===> ordinal encoder

df = pd.read_csv("/content/tips - tips.csv")

df.head()

df.dropna()

y = df['total_bill']

df = df.drop(columns=['total_bill', 'tip', 'size'])

# y = df['total_bill']

from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(categories=[
    ['Female', 'Male'],
    ['No', 'Yes'],
    ['Sun', 'Sat', 'Thur', 'Fri'],
    ['Dinner', 'Lunch']
])

X = oe.fit_transform(df)

X = pd.DataFrame(X, columns=df.columns)

X.head()