# -*- coding: utf-8 -*-
"""pipeline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C4gkzZYwE5Y8sbvBGuKvW9sfliVK1-BE
"""

data :-

import numpy as np
import pandas as pd

df = pd.read_csv("/content/covid_toy - covid_toy (1).csv")

df.head()

from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

x = df.drop(columns =['has_covid'])
y = df['has_covid']
x_train,x_test , y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=2)

# define the columns that need to be preprocessed
categorical_features = ['cough', 'city', 'gender']
numerical_features = ['age','fever']

# create transformers
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])
categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])
#combine transformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features)
    ])
#create the pipeline
clf = Pipeline(steps=[('preprocessor', preprocessor),
                      ('classifier', LogisticRegression())])

df.head()

preprocessor

# tips

df = pd.read_csv("/content/tips - tips.csv")

df.head()

from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

x = df.drop(columns =['total_bill'])
y = df['total_bill']
x_train,x_test , y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=2)

# define the columns that need to be preprocessed
categorical_features = ['sex',	'smoker','day',	'time']
numerical_features = ['tip','size']

# create transformers
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])
categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

#combine transformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features)
    ])

#create the pipeline
clf = Pipeline(steps=[('preprocessor', preprocessor),
                      ('classifier', LogisticRegression())])

preprocessor

df.head()



df = pd.read_csv("/content/insurance - insurance.csv")

df.head()

from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

x = df.drop(columns =['charges'])
y = df['charges']
x_train,x_test , y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=2)

# define the columns that need to be preprocessed
categorical_features = ['sex',	'smoker','region']
numerical_features = ['age','size','bmi',]

# create transformers
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])
categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

#combine transformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features)
    ])

#create the pipeline
clf = Pipeline(steps=[('preprocessor', preprocessor),
                      ('classifier', LogisticRegression())])

preprocessor

# backend bna ke dena h