# -*- coding: utf-8 -*-
"""practice_sc_day_3_insurance data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hDami-2ptsRuAN_O_U8T1AmOYaauVm6V
"""

import numpy as np
import pandas as pd

df = pd.read_csv("/content/insurance - insurance.csv")
df

df.isnull().sum()

df.head(12)

df['sex'] = df['sex'].map({'male':0,'female':1})
df['smoker'] = df['smoker'].map({'yes':1,'no':0})
df['region'] = df['region'].map({'southwest':0,'southeast':1,'northwest':2,'northeast':3})

df.head()

df.describe()

x = df.drop(columns=['charges'])
x

y = df['charges']
y

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

np.round(x_train.describe(),2)

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

x_train_sc = sc.fit_transform(x_train)

x_test_sc = sc.transform(x_test)

x_train_sc

x_train_new = pd.DataFrame(x_train_sc, columns= x_train.columns)



type(x_train_new)

np.round(x_train_new.describe(),2)