# -*- coding: utf-8 -*-
"""Practice_Encoding_scaling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JGd1v8FMssUPzi8aydG2MNIx95Q-UBPT
"""

import numpy as np
import pandas as pd

df = pd.read_csv('/content/Churn_Modelling - Churn_Modelling.csv')
df.drop(columns=['Surname'], inplace=True)
df.head(3)

df.shape

df.isnull().sum()

df['Geography'].value_counts()

df['Gender'].value_counts()

"""### Label Encoding"""

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Geography'] = le.fit_transform(df['Geography'])
df['Gender'] = le.fit_transform(df['Gender'])

df.head(3)

"""### Ordinal Encoding"""

df1 = pd.read_csv('/content/Churn_Modelling - Churn_Modelling.csv')
df1.drop(columns=['Surname'], inplace=True)
df1.head(3)

from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(categories=[['France', 'Germany', 'Spain'], ['Male', 'Female']])

oe_ar = oe.fit_transform(df1[['Geography', 'Gender']])
oe_ar

oe_df1 = pd.DataFrame(oe_ar, columns=df1[['Geography', 'Gender']].columns)
oe_df1.head(2)

df1[['Geography', 'Gender']] = oe_df1
df1.head(2)

"""### get_dummies"""

df2 = pd.read_csv('Churn_Modelling - Churn_Modelling.csv')
df2.drop(columns=['Surname'], inplace=True)
df2.head(3)

a = pd.get_dummies(df2,columns=['Geography', 'Gender'], drop_first=True, dtype=int)

a.info()

"""### OneHotEncoding"""

df3 = pd.read_csv('Churn_Modelling - Churn_Modelling.csv')
df3.drop(columns=['Surname'], inplace=True)
df3.head(3)

from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(drop='first', sparse_output=False, dtype=np.int32)

ohe_ar = ohe.fit_transform(df[['Geography', 'Gender']])

ohe_ar

"""### Standardization"""

df.head(3)

x = df.drop(columns='Exited')
y = df['Exited']

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y,test_size=0.20, random_state=42)

np.round(x_train.describe(), 2)

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

x_train_sc = sc.fit_transform(x_train)

# x_train_sc

new_x_train = pd.DataFrame(x_train_sc, columns=x.columns)

np.round(new_x_train.describe(), 2)

"""### minmaxScalling"""

x = df1.drop(columns='Exited')
y = df1['Exited']

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y,test_size=0.20, random_state=42)

np.round(x_train.describe(), 2)

from sklearn.preprocessing import MinMaxScaler

mm = MinMaxScaler()

x_train_mm = mm.fit_transform(x_train)

x_train_new = pd.DataFrame(x_train_mm, columns=x_train.columns)

np.round(x_train_new.describe(),2)

print