# -*- coding: utf-8 -*-
"""practice_on_tips_data_nd

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i3GsFoZAsDA0YvGZRo_j72UVnXmlymeF
"""

import numpy as np
import pandas as pd

df = pd.read_csv("/content/tips - tips.csv")
df

# df.isnull().sum()

df['sex'] = df['sex'].map({'Male':0,'Female':1})
df['smoker'] = df['smoker'].map({'No':0,'Yes':1})
df['day'] = df['day'].map({'Thur':0,'Fri':1,'Sat':2,'Sun':3})
df['time'] = df['time'].map({'Lunch':0,'Dinner':1})

df.head()

df.describe()

x = df.drop(columns=['total_bill'])
x

y = df['total_bill']
y

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

np.round(x_train.describe(),2)

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

x_train_sc = sc.fit_transform(x_train)



x_train_sc

x_train_new = pd.DataFrame(x_train_sc, columns= x_train.columns)

type(x_train_new)

np.round(x_train_new.describe(),2)  #std.mean

