# -*- coding: utf-8 -*-
"""practice_data_divide,normal_distribution, normalization , standard scalar, encoding , label encoding

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PitpzV7tAet9dyrYayzbCd5PM7dXfe5c
"""

import numpy as np
import pandas as pd

df = pd.read_csv("/content/cars - cars.csv")

df.head()

df.isnull().sum()

df.shape

# data divide
# step 1 imporyt libraries
# step 2 data load in csv format
# step 3 null values check if null values h to unhe fill kro using fillna or mean se mtlb avg value
# df['fever'] = df['fever'].fillna df['fever'].mean()
# Note: ML models null/NaN values handle nahi kar sakte. Isliye pehle missing values ko fill ya drop
# karna zaroori hai.
#  then
# step 4 :- x or y ko separate kro x(input: sab columns except target) or y mai only target data
# x = df.drop(columns=['has_covid']) # input: sab columns except target
# y = df['has_covid'] # output: sirf target column

# step 5 :- train test split
# x_train, x_test, y_train, y_test = train_test_split( x, y, test_size=0.2, # 20% test, 80% train
# random_state=42 # reproducibility ke liye)

import pandas as pd
import numpy as np

df = pd.read_csv("/content/cars - cars.csv")

df.head(3)

df.shape

df.isnull().sum()

# df[column]=df[column].fillna(df[column].mean())

x = df.drop(columns=['selling_price'])

y = df['selling_price']

from sklearn.model_selection import train_test_split

x_train, x_test , y_train, y_test = train_test_split(x,y , test_size =0.2, random_state = 42)

print("total_data_shape:", df.shape)

print("x_input_data_shape :", x.shape)

print("y_input_data_shape :",y.shape)

print("x_test_data_shape:",x_test.shape)

print("x_test_data_shape:",x_train.shape)

print("y_test_data_shape:",y_test.shape)

print("y_train_data_shape:",y_train.shape)

"""normal distribution"""

# step 1 import libraries
# step 2 load data
# step 3 handle missing values using fillna with mean
# step 4 convert categorical data to numerical
# check data using describe or value counts
# step 5 data divide x and y
# step 6 data ko split
# step 7 check data using round function
# step 6 import standard scalar fun
# step 7 fit transform apply krna
# step 8 data ko array se dataframe m convert krna
# step 9 last m round function use krke check kro

import pandas as pd
import numpy as np

df = pd.read_csv("/content/click - click.csv")

df.head(10)

df.shape

df.isnull().sum()

# ad topic line , city , gender, country
# categorigal data ko numerical m convert krna

df['Gender'] = df['Gender'].map({'Male':0,'Female':1})

df.drop(columns=['Ad Topic Line', 'City','Country'])

df.describe()

x = df.drop(columns=['Clicked on Ad', 'Ad Topic Line', 'City', 'Country', 'Timestamp'])
x

y = df['Clicked on Ad']
y

from sklearn.model_selection import train_test_split

x_train , x_test , y_train , y_test = train_test_split(x,y,test_size = 0.2 , random_state = 42)

np.round(x_train.describe(),2)

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

x_train_sc = sc.fit_transform(x_train)

x_train_sc

x_train_new = pd.DataFrame(x_train_sc, columns= x_train.columns)

type(x_train_new)

np.round(x_train_new.describe(),2)

type(x_train_new)

"""**normalization**"""

# step 1 import libraries
# step 2 load data
# or using dropna()
# step 3 handle missing values using fillna with mean
# step 4  convert categorical data to numerical
# step 5 divide data
# step 6 using train test split
# step 7 apply min max scalling
# same as standard scaler but  standard scalar replace with min max scalling

import pandas as pd
import numpy as np

df = pd.read_csv("/content/cars - cars.csv")
df.head(30)

df.isnull().sum()

df = df.dropna()

df['fuel'] = df['fuel'].map({'Petrol':0,'Diesel':1,'LPG':2})

df['seller_type'] = df['seller_type'].map({'Individual':0,'Dealer':1})

df['transmission'] = df['transmission'].map({'Automatic':0,'Manual':1})

df.head()

x = df.drop(columns=['selling_price','name','owner'])
x

y = df['selling_price']
y

df.describe()

from sklearn.model_selection import train_test_split

x_train , x_test , y_train ,y_test = train_test_split( x,y, test_size = 0.2 , random_state = 42)

np.round(x_train.describe(),2)

from sklearn.preprocessing import MinMaxScaler

mn = MinMaxScaler()

x_train_mn = mn.fit_transform(x_train)

np.round(x_train.describe(),2)

x_train_new = pd.DataFrame(x_train_mn, columns = x_train.columns)

type(x_train_new)

np.round(x_train_new.describe(),2)

