# -*- coding: utf-8 -*-
"""ridge_lasso_elastic_net

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c3fyKQxMiZWvStbcIFmB_jXIquyASjPC
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge, Lasso , ElasticNet
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler

df = pd.read_csv("/content/insurance - insurance.csv")

from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()

df['sex'] = lb.fit_transform(df['sex'])
df['smoker'] = lb.fit_transform(df['smoker'])
df['region'] = lb.fit_transform(df['region'])

x = df.drop(columns=['charges'])
y = df['charges']

x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=42)

scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

#ridge ::::
# ridge adds l2 penality
# it reduces coefficient values but does not make them zero

Ridge_model = Ridge(alpha=0.1)
Ridge_model.fit(x_train,y_train)

Ridge_pred = Ridge_model.predict(x_test)

Ridge_mse = mean_squared_error(y_test,Ridge_pred)
Ridge_r2 = r2_score(y_test,Ridge_pred)

print("MSE :",Ridge_mse)
print("R2 Score :",Ridge_r2)
print("Coefficients :",Ridge_model.coef_)

# lasso ads l1 penality
# it can make some coefficients exactly zero to performs feture selection

Lasso_model = Lasso(alpha=0.1)
Lasso_model.fit(x_train,y_train)

Lasso_pred = Lasso_model.predict(x_test)

Lasso_pred = Lasso+model.predict(x_test)

Lasso_mse = mean_squared_error(y_test,Lasso_pred)
Lasso_r2 = r2_score(y_test,Lasso_pred)

print("MSE :",Lasso_mse)
print("R2 Score :",Lasso_r2)
print("\nCoefficients :",Lasso_model.coef_)

Elastic_model = ElasticNet(alpha=0.1,l1_ratio=0.5)
Elastic_model.fit(x_train,y_train)

Elastic_pred = Elastic_model.predict(x_test)

Elastic_mse = mean_squared_error(y_test,Elastic_pred)
Elastic_r2 = r2_score(y_test,Elastic_pred)

print("MSE :",Elastic_mse)
print("R2 Score :",Elastic_r2)
print("\nCoefficients :",Elastic_model.coef_)

#cross validation
from sklearn.linear_model import LassoCV

Lasso_cv = LassoCV(
    alphas=[0.001,0.01,0.1,1,10],
    cv = 5,
    random_state=42
)

Lasso_cv.fit(x_train,y_train)
print("Best Alpha:",Lasso_cv.alpha_)

from sklearn.linear_model import ElasticNetCV
Elastic_cv = ElasticNetCV(
     l1_ratio=[0.1,0.3,0.5,0.7,0.9,1],
     alphas=[0.001,0.01,0.1,1,10],
     cv=5,
     random_state=42
 )
Elastic_cv.fit(x_train,y_train)
print("Best Alpha:",Elastic_cv.alpha_)
print("Best L1 Ratio:",Elastic_cv.l1_ratio_)

# machine learning model or tbale diff btw ridge lasso elastic net, diff btw rmse or mae