# -*- coding: utf-8 -*-
"""standardization_29_April

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l5bCExyVhWV-xtqdAExcwH8ujE7HLfAE
"""

import numpy as np
import pandas as pd

df = pd.read_csv("/content/insurance - insurance.csv")

df.head()

sex , smoker , region

df['region'].value_counts()

df['sex'] = df['sex'].map({"female":1,"male":0})
df['smoker'] = df['smoker'].map({"yes":1,"no":0})
df['region'] = df['region'].map({"southeast":1,"southwest":2,"northwest":3,"northeast":4})

df.head()

x = df.drop(columns = ['charges'])
y = df['charges']

from sklearn.model_selection import train_test_split

x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=42)

np.round(x_train.describe(),2)

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

x_train_sc = sc.fit_transform(x_train)

x_train_new = pd.DataFrame(x_train_sc, columns = x_train.columns)

type(x_train_sc)

np.round(x_train_new.describe(),2)