# -*- coding: utf-8 -*-
"""tips_data_column_transformation_30_april

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18S2F0qnrZkcuphqv40LTPgayYz5GAYdF
"""

# tips data set ke upar column transformer  without apply column transformer

import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import  OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

df =  pd.read_csv("/content/tips - tips.csv")

df

df.isnull().sum()

X = df.drop(columns=['total_bill'])
y = df['total_bill']

from sklearn.model_selection import train_test_split

x_train , x_test , y_train , y_test = X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

x_train

# manually type

si = SimpleImputer(strategy='mean')
x_train_tip = si.fit_transform(x_train[['tip']])
x_test_tip = si.transform(x_test[['tip']])
x_train_tip.shape

oe = OrdinalEncoder(categories=[['Thur', 'Fri', 'Sat', 'Sun'], ['Lunch', 'Dinner']])
x_train_day_time = oe.fit_transform(x_train[['day', 'time']])
x_test_day_time = oe.transform(x_test[['day', 'time']]) # test data
x_train_day_time.shape

ohe = OneHotEncoder(drop='first', sparse_output=False)
x_train_sex_smoker = ohe.fit_transform(x_train[['sex', 'smoker']])
x_test_sex_smoker = ohe.transform(x_test[['sex', 'smoker']])
x_train_sex_smoker.shape

x_train.shape

x_train_size = x_train[['size']].values
x_test_size = x_test[['size']].values

x_train_transformed = np.concatenate((x_train_tip, x_train_day_time, x_train_sex_smoker, x_train_size), axis=1)
x_test_transformed = np.concatenate((x_test_tip, x_test_day_time, x_test_sex_smoker, x_test_size), axis=1)

x_train_transformed.shape

"""# by the help of column transformer"""

from sklearn.compose import ColumnTransformer

transformer = ColumnTransformer(transformers=[
    ('tnf1', SimpleImputer(), ['tip']), # Numerical column (Imputation)
    ('tnf2', OrdinalEncoder(categories=[['Thur', 'Fri', 'Sat', 'Sun'], ['Lunch', 'Dinner']]), ['day', 'time']), # Ordinal
    ('tnf3', OneHotEncoder(drop='first', sparse_output=False), ['sex', 'smoker'])
], remainder='passthrough')

transformer.fit_transform(x_train).shape