# -*- coding: utf-8 -*-
"""titanic_outliers

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PmMDy9ST6xlvOHaIY5-8DvqYnDA-64S8
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/titanic - titanic.csv")

df.head()

df['Age'].describe()

sns.boxplot( x = df['Age'])

# Finding Percentile

percentile25 = df['Age'].quantile(0.25)
percentile25

percentile75 = df['Age'].quantile(0.75)
percentile75

IQR =   percentile75 - percentile25
IQR

upper_limit = percentile75 + 1.5*IQR
upper_limit

lower_limit = percentile25 - 1.5*IQR
lower_limit

# Finding our outlier

df[df['Age'] < upper_limit ]

df[df['Age'] < lower_limit ]

# Trimming (Outlier Removing technique 1)

newdf = df[df['Age'] < upper_limit]

newdf

# comparision

plt.figure(figsize=(15,5))

plt.subplot(222)
sns.boxplot(x=df['Age'])


plt.figure(figsize=(15,5))

plt.subplot(222)
sns.boxplot(x=newdf['Age'])

# Capping (Outlier Removing technique 2)

new_df_cap = df.copy()

new_df_cap['Age'] = np.where(
    new_df_cap['Age'] > upper_limit,
    upper_limit,


    np.where(
        new_df_cap['Age'] < lower_limit,
        lower_limit,
        new_df_cap['Age']
    )
)

# new_df_cap['Age'].max()
new_df_cap.head()

plt.figure(figsize=(15,8))

plt.subplot(222)
sns.boxplot(x=df['Age'])


plt.figure(figsize=(15,5))

plt.subplot(222)
sns.boxplot(x=new_df_cap['Age'])

